version: 2

sources:

    - name: src_actions
      schema: default
      # loader: S3
      description: "product analitica"

      tables:

        - name: src_actions
          description: "data loaded by python"
          identifier: pre_users_actions
        - name: s3actions0
          description: "old data from s3"
          identifier: s3connector_actions0
        - name: s3actions1
          description: "old data from s3"
          identifier: s3connector_actions1
        - name: actions_row
          description: "all old data from s3"
          identifier: S3_users_actions_row

        - name: actions_new
          description: "new data from postgress"
          identifier: client_events

    - name: clusters
      schema: default
      description: ""

      tables:
          - name: clients
            identifier: clients

    - name: ym
      schema: default
      # loader: S3
      description: "data from yandex metrica"

      tables:
        - name: visits
          description: "visits"
          identifier: visits_all

    
    
    - name: src_back
      schema: prod_copies
      # loader: S3
      description: ""

      tables:

        - name: src_users
          description: "all users"
          identifier: users
        
        - name: withdraws_updates
          description: "withdraws updates"
          identifier: withdraws_updates